# Generated by Django 5.0.7 on 2024-07-28 14:54

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["email", "username"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                db_comment="Photo of the user.",
                help_text="Photo of the user.",
                null=True,
                upload_to=users.models.create_custom_path_for_photo,
            ),
        ),
        migrations.CreateModel(
            name="ResidencePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        db_comment="Name of the user's country of residence. Not required.",
                        help_text="Name of the user's country of residence. Not required.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_comment="Name of the user's city of residence. Not required.",
                        help_text="Name of the user's city of residence. Not required.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "code_country",
                    models.CharField(
                        blank=True,
                        db_comment="Country and territory codes (ISO 3166-1).",
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["country", "city"],
                "indexes": [
                    models.Index(
                        fields=["country", "city"],
                        name="users_resid_country_7eb2ec_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="residence_place",
            field=models.ForeignKey(
                blank=True,
                db_comment="Residence place of the user.",
                help_text="Residence place of the user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.residenceplace",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username", "first_name", "last_name"],
                name="users_user_usernam_1d8d1d_idx",
            ),
        ),
    ]
