# Generated by Django 5.0.7 on 2024-07-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_photo_residenceplace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Name of the user's city of residence. Not required.",
                        help_text="Name of the user's city of residence. Not required.",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name="residenceplace",
            new_name="users_resid_country_9f4c91_idx",
            old_name="users_resid_country_7eb2ec_idx",
        ),
        migrations.AlterField(
            model_name="residenceplace",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City of the user's residence. Not required.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.city",
            ),
        ),
    ]
