# Generated by Django 5.0.7 on 2024-07-29 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_users_user_usernam_1d8d1d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                db_comment="Users that follow this user.",
                help_text="Users that follow this user.",
                related_name="my_following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="my_subscriptions",
            field=models.ManyToManyField(
                db_comment="Users this user is subscribed to.",
                help_text="Users this user is subscribed to.",
                related_name="my_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
