# Generated by Django 5.0.7 on 2024-07-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="residenceplace",
            name="city",
        ),
        migrations.AlterModelOptions(
            name="residenceplace",
            options={"ordering": ["country"]},
        ),
        migrations.RemoveIndex(
            model_name="residenceplace",
            name="users_resid_country_9f4c91_idx",
        ),
        migrations.AddIndex(
            model_name="residenceplace",
            index=models.Index(
                fields=["country", "code_country"],
                name="users_resid_country_fc5eb7_idx",
            ),
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
