# Generated by Django 5.0.7 on 2024-07-29 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_user_followers_user_my_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                db_comment="Date of birth of the user.",
                help_text="Date of birth of the user.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                help_text="Users that follow this user.",
                related_name="my_following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="my_subscriptions",
            field=models.ManyToManyField(
                help_text="Users this user is subscribed to.",
                related_name="my_subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["birth_date"], name="users_user_birth_d_26cb3b_idx"
            ),
        ),
    ]
