# Generated by Django 5.0.7 on 2024-07-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["date_joined"]},
        ),
    ]
