# Generated by Django 5.0.7 on 2024-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("username__isnull", False)),
                fields=("username",),
                name="unique_username",
                violation_error_message="A user with that username already exists.",
            ),
        ),
    ]
