# Generated by Django 5.0.7 on 2024-07-31 09:02

import django.db.models.deletion
import post.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        db_comment="The content of the comment",
                        help_text="Enter the content of the comment, up to 300 characters",
                        max_length=300,
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True,
                        db_comment="The date when the comment was created",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_comment="The unique name of the hashtag",
                        help_text="Enter the unique name of the hashtag",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["-name"], name="post_hashta_name_03cb01_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="The title of the post",
                        help_text="Enter the title of the post, up to 100 characters",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        db_comment="The content of the post",
                        help_text="Enter the content of the post, up to 3000 characters",
                        max_length=3000,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        db_comment="The image associated with the post",
                        help_text="Upload an image to be associated with the post",
                        null=True,
                        upload_to=post.models.create_custom_path_for_image,
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True,
                        db_comment="The date when the post was created",
                    ),
                ),
                (
                    "comments",
                    models.ManyToManyField(related_name="posts", to="post.comment"),
                ),
                (
                    "hashtags",
                    models.ManyToManyField(related_name="posts", to="post.hashtag"),
                ),
                ("likes", models.ManyToManyField(related_name="posts", to="post.like")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(fields=["title"], name="post_post_title_2a5626_idx")
                ],
            },
        ),
    ]
