# Generated by Django 5.0.7 on 2024-08-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                db_comment="The date and time when the post is scheduled to be created",
                null=True,
            ),
        ),
    ]
