# Generated by Django 5.0.7 on 2024-08-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hashtag",
            options={"ordering": ["tag"]},
        ),
        migrations.RemoveIndex(
            model_name="hashtag",
            name="post_hashta_name_03cb01_idx",
        ),
        migrations.RenameField(
            model_name="hashtag",
            old_name="name",
            new_name="tag",
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(fields=["-tag"], name="post_hashta_tag_ca6162_idx"),
        ),
    ]
