# Generated by Django 5.0.7 on 2024-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_hashtag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashtag",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="tag",
            field=models.CharField(
                db_comment="The unique name of the hashtag",
                help_text="Enter the unique name of the hashtag",
                max_length=50,
                unique=True,
            ),
        ),
    ]
