# Generated by Django 5.0.7 on 2024-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_hashtag_id_alter_hashtag_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hashtag",
            name="id",
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="tag",
            field=models.CharField(
                db_comment="The unique name of the hashtag",
                help_text="Enter the unique name of the hashtag",
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
