# Generated by Django 5.0.7 on 2024-08-05 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_hashtag_id_alter_hashtag_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="posts_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
