# Generated by Django 5.0.7 on 2024-08-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_post_likes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
